export enum ComplaintType {
    SINISTRE_AUTOMOBILE = 'SINISTRE_AUTOMOBILE',
    SINISTRE_HABITATION = 'SINISTRE_HABITATION',
    ASSURANCE_SANTE = 'ASSURANCE_SANTE',
    ASSURANCE_VIE = 'ASSURANCE_VIE',
    RETARD = 'RETARD',
    ERREUR_FACTURATION = 'ERREUR_FACTURATION',
    RESILIATION_CONTRAT = 'RESILIATION_CONTRAT',
    SERVICE_CLIENT_INSATISFAISANT = 'SERVICE_CLIENT_INSATISFAISANT'
  }